Fix uncovered bug related to data type when not null
Odoo 13.0 returns date objects from Date fields, rather than strings,
so it's a bug to try to parse the datetime.date object as a date string.

Here's the exception traceback:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 139, in dispatch_rpc
    result = dispatch(method, params)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 41, in dispatch
    res = fn(db, uid, *params)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 181, in execute
    res = execute_cr(cr, uid, obj, method, *args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 165, in execute_cr
    result = odoo.api.call_kw(recs, method, args, kw)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2915, in read
    vals[name] = convert(record[name], record, use_name_get)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5610, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1020, in __get__
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1105, in compute_value
    records._compute_field_value(self)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3915, in _compute_field_value
    getattr(self, field.compute)()
  File "/mnt/extra-addons-bundles/OpusVL_Odoo-UK-Format-Reports/UK_Reports/models/account_move_line.py", line 45, in _compute_statement_account_values
    record.statement_account_overdue = record.statement_account_value
  File "/mnt/extra-addons-bundles/OpusVL_Odoo-UK-Format-Reports/UK_Reports/models/account_move_line.py", line 37, in is_overdue
    return on_this_date > moveline.date_maturity
TypeError: strptime() argument 1 must be str, not datetime.date